### ISSUE TITLE
Crash after install on nodebb 0.6.x

### ISSUE THREAD

**Issue by h3ku** [akhoury/nodebb-plugin-import-vbulletin#3]
TypeError: Cannot read property 'buildHeader' of undefined

**Comment by h3ku** [comment]
Solved

**Comment by akhoury** [comment]
for anyone else landing here, you don't really need to install nodebb-plugin-import-vbulletin (or any nodebb-plugin-import-{NAME}) for that matter, just install *nodebb-plugin-import* and it will install the "child" plugins for you.
