### ISSUE TITLE
utf8 data

### ISSUE THREAD

**Issue by sohrabafard** [akhoury/nodebb-plugin-import-vbulletin#4]
Hello,
about "vbulletin" to "nodebb" migration using nodebb import plugin, the contents were transferred as follows:

Ù„Ø·ÙØ§ ÙÙ‚Ø· Ú©ØªØ¨ Ùˆ Ø¬Ø²ÙˆØ§ØªÛŒ Ø±Ø§ Ù‚Ø±Ø§Ø± Ø¯Ù‡ÛŒØ¯ Ú©Ù‡ Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡ ÛŒ Ø¢Ù† Ù‡Ø³ØªÛŒØ¯ Ùˆ ÛŒØ§ Ø§Ø² Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡ ÛŒ Ø¢Ù† Ø§Ø¬Ø§Ø²Ù‡ Ø¯Ø§Ø±ÛŒØ¯.

Who can help me?

**Comment by akhoury** [comment]
what was the original content?

**Comment by akhoury** [comment]
closing as duplicate
