### ISSUE TITLE
DB Host is always set to localhost

### ISSUE THREAD

**Issue by avdeveloper** [akhoury/nodebb-plugin-import-vbulletin#8]
https://github.com/akhoury/nodebb-plugin-import-vbulletin/blame/master/index.js#L21

I set the host of db to a domain name and when I ran the app using
```
NODE_ENV=development node app
```

the logs showed that it's trying to connect to [my-username]@'localhost'

**Comment by akhoury** [comment]
Sorry for the delay on this one, are you still having issues? that line you linked to only fallsback to `localhost` if nor `dbhost` nor `host` are set.
feel free to reopen
